export function escapeXml(value) { return String(value).replace(/[<>&"']/g, char => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' })[char]); }
/** SVG embeds masks and source, but keeps every visible glyph as editable text. */
export function createSvg(analysis, settings, sourceUrl, effectMaskUrl, originalMaskUrl) {
  for (const url of [sourceUrl, effectMaskUrl, originalMaskUrl]) if (!/^data:image\/png;base64,[a-z\d+/=]+$/i.test(url)) throw new Error('SVG resources must be embedded PNG images.');
  const { width, height } = analysis;
  const image = url => `<image width="${width}" height="${height}" href="${url}"/>`;
  const glyphs = analysis.cells.map(c => `<text x="${c.x.toFixed(2)}" y="${c.y.toFixed(2)}" fill="rgb(${c.color.join(',')})" opacity="${(c.alpha * settings.asciiOpacity).toFixed(3)}"${settings.rotation ? ` transform="rotate(${settings.rotation} ${c.x} ${c.y})"` : ''}${settings.glow && c.brightness >= settings.glowThreshold ? ' filter="url(#glow)"' : ''}>${escapeXml(c.char)}</text>`).join('');
  const scanlines = settings.scanlines ? `<pattern id="scan" width="1" height="4" patternUnits="userSpaceOnUse"><rect width="1" height="1" fill="black" opacity="${settings.scanlines}"/></pattern>` : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" color-interpolation="sRGB" color-interpolation-filters="sRGB"><title>Flower export</title><defs><mask id="effect" mask-type="luminance">${image(effectMaskUrl)}</mask><mask id="original" mask-type="luminance">${image(originalMaskUrl)}</mask><filter id="glow" x="-200%" y="-200%" width="500%" height="500%"><feGaussianBlur stdDeviation="${settings.glowRadius / 2}"/><feComponentTransfer><feFuncA type="linear" slope="${settings.glow}"/></feComponentTransfer><feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge></filter><radialGradient id="vignette"><stop offset=".2" stop-opacity="0"/><stop offset="1" stop-opacity="${settings.vignette}"/></radialGradient>${scanlines}<filter id="merge" x="0" y="0" width="100%" height="100%" primitiveUnits="userSpaceOnUse"><feImage href="${sourceUrl}" width="${width}" height="${height}" result="source"/><feImage href="${originalMaskUrl}" width="${width}" height="${height}" result="selection"/><feColorMatrix in="selection" type="matrix" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0" result="alphaMask"/><feComposite in="source" in2="alphaMask" operator="in" result="preserved"/><feComposite in="SourceGraphic" in2="preserved" operator="arithmetic" k1="0" k2="1" k3="1" k4="0"/></filter></defs><g filter="url(#merge)"><g mask="url(#effect)">${settings.transparent ? '' : `<rect width="100%" height="100%" fill="${settings.background}"/>`}<g opacity="${settings.originalOpacity}">${image(sourceUrl)}</g><g font-family="monospace" font-size="${analysis.fontSize}" text-anchor="middle" dominant-baseline="central">${glyphs}</g>${settings.scanlines ? '<rect width="100%" height="100%" fill="url(#scan)"/>' : ''}${settings.vignette ? '<rect width="100%" height="100%" fill="url(#vignette)"/>' : ''}</g></g></svg>`;
}
